print("SIM Swap Simulation")
print("Attacker calls mobile carrier pretending to be the victim...")
print("Provides stolen personal details (DOB, ID, Address)")
print("Carrier verifies weak KBA (knowledge-based authentication)...")
print("SIM card swapped!  Control of number transferred to attacker.")
